#pragma config(Motor,  motorA,          addon,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

What John thinks he is when he is at robotics club:

                                            .-.
                                          .-.( ; )-.
                                         ( ;(); ).-.)
                                        ( ; )(:)( ; )
                                         (:)   ( ; )
                                                (:)
                                             .-'._.`-.
                                            /         `.                 _,,...._
                                            | /`-.     .                |```````.```-.
                                            | |   `.__.|                |           `-.`.
                                            | |   == \=|                |              `.\
                               .--.---'-----\  \     //                 |                \\_
                             .'    `.\ _:,----. \    /------.           |         __..---''
                           .'        )) /.     \ \__/ / \    `.          __..---''_..--''-''
                         .'         // ,'       `----'  |      \__..,--''__...--''       ||
                       .'          ; : |           |   _....--''  _...--''   .-.         ||
                      /-         .' |_ \       __..--''  _,.,..--':   |     / .(_\       ||
                     /_.+-+-+..___ .' `-,._.-''  _,..---'.         `.+.+ +.+  ) / )      ||
                    <( + + + .-.-./      (  _.-'' '   /   `.       (+ + + + +  (_//      ||
                     `+MJP..( (( (|       ;"    .'   ;      `.       + + + + ._(_/)      ||
                    '''    __\ \\ \\     ;    .'  .-'         ``-----'+'+'     (_/       '|
                    ..---''   `-'`-'`._.'    _..-'\                     |          /\    /\
                               .  ' `--  '--'      \                    |         /  )  /  \
                               |   /                |                   \    _,,-;   `'- -.:
                               |  |    .---.   .-------.                 _.-' _,'            `. 
                              _`  (_.-'     `.((=#=#=#=#)            _.-'                     `. 
                                   \         \ ((=#=#=#=)         .-'                  . -.    ( 
                                    \         \ (#=#=#=#______..-'             /      `.(_.'    \
   '     /'                          \         . =#=#=      .' |                                 .
  /     /'                            \     _^_ . #=       / |                                    \
 /     '                      \        \  .'   `.\        ( \                                      .
.      ;                      `.        \/       \         `. \                                     .\
|     '                        |        (o        )         `.                 /  `-.__\.        _    .
|    '                                   |\      /|          `.              ,'          `.  .  ( \   |
|    |                        ,|         | `----' |           |             /              `\ `. `-' .'
|    |                       /           |        |/           |          .'                 '--\.,-'
|    |                                   |      .-'/           \         /
|    |                                   `.    / .'             )       /
|    |                                    `.  / / |             |+.    /+
|    |                                    `. / / |              |  `+.+'
| .-.|                                    | / /  |              |     /
|'.-.|                                    / / ---.              |    /
''   |                                *-.| |      `--._         |   '.
     |                                 `,| |          _>        | .' |
     |                                   (_(_`-------'          |'   |
     |                                                          |    |
     |.-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-.   .-. | _.-'
     |.-.`-'.-.`-'.-.`-'.-.`-'.-.`-'.-.`-'.-.`-'.-.`-'.-.`-'_.-'
     '   `-'   `-'   `-'   `-'   `-'   `-'   `-'   `-'   `-'


What John actually looks like at robotics club:

            (.,------...__
         _.'"             `.
       .'  .'   `, `. `.    `
      . .'   .'/''--...__`.  \
     . .--.`.  ' "-.     '.  |
     ''  .'  _.' .())  .--":/
     ''(  \_\      '   (()(
     ''._'          (   \ '
     ' `.            `--'  '
      `.:    .   `-.___.'  '
       `.     .    _  _  .'
         )       .____.-'
       .'`.        (--..
     .' \  /\      / /  `.
   .'    \(  \    /|/     `.
 .'           \__/          `.
/      |        o      |      \
       |               |      |
       
Images from http://www.chris.com/ascii/
*/

int linefollow()
{
}

int getring()
{
 	motor[addon] = -30;
	wait10Msec(100);
	motor[addon] = 0;
	return 0;
}

int dropring()
{
	motor[addon] = 30;
	wait10Msec(100);
	motor[addon] = 0;
	return 0;
}

int deploy_fork()
{
	motor[addon] = 30;
	wait10Msec(15);
	motor[addon] = 0;
	return 0;
}

int pushblocks()
{
}

int turn_left(float numDegrees)
{
	motor[right] = 20;
	motor[left] = 0;
	wait10Msec((240.0 / 90.0) * numDegrees);
	motor[right] = 0;
	return 0;
}

int turn_right(float numDegrees)
{
	motor[left] = 20;
	motor[right] = 0;
	wait10Msec((240.0 / 90.0) * numDegrees);
	motor[left] = 0;
	return 0;
}

int forward(float num) // Move forward one foot
{
	motor[left] = 20;
	motor[right] = 20;
	wait10Msec(320.0 * num);
	motor[left] = 0;
	motor[right] = 0;
	return 0;
}

int backward(float num)
{
	motor[left] = -20;
	motor[right] = -20;
	wait10Msec(320.0 * num);
	motor[left] = 0;
	motor[right] = 0;
	return 0;
}

task main()
{
	forward(1.0);
	getring();
	backward(1.0);
	dropring();
}
